[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
image = "0.25.2"
log = "0.4.22"
texture_packer = "0.29.0"
anyhow = "1.0.89"
ron = "0.9.0-alpha.0"
